<?php 
$allCars= $block->getCarList();
$email = $block->getCustomerEmail();
?>

<h2 id="response"></h2>
<div class="container">
  <div class="row">
  	 <div class="main-flex-dv">
  	<?php $i =1;
  	foreach($allCars['cars'] as $car){
			$imageUrl = $block->getCarImageById($car->id);?>
<div class= "cardata  cardetail<?= $i ?>">
   
      <img class="image" src=<?= $imageUrl ?> alt="<?= $car->model ?>" width="150" height="auto">
      <div class="data-flex"></div>
    	<p class="car_id">Cara id =<?= $car->id ?></p><br>
    	<p class="year" >year  =  <?= $car->year ?></p><br>
    	<p class="make" >make  =  <?= $car->make ?></p><br>
    	<p class="model" >model  =  <?= $car->model ?></p><br>
        <p class="email" hidden >email  =  <?= $email ?></p><br>
      <input type="checkbox" id="car" class="car" name="car" value="<?= $car->id?>">

    </div>

   <?php }?>
  
       </div>
       <div class="main-flex-dv">
        <button type="button" id="submit">Submit</button>
      </div>
  </div>
</div>



<script type="text/x-magento-init">
{
"*":{"Razoyo_CarProfile/js/carsave": {}}
}
</script>